development: &global_settings
  database: dadbdc_development
  host: 127.0.0.1
  port: 27017

test:
  database: dadbdc_test
  <<: *global_settings

production:
  database: dadbdc_prod
  #username: username
  #password: password
  <<: *global_settings
